name: Test

on:
  push:
    branches:
      - main
      - master
      - next

  pull_request:
    types:
      - closed

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run test

  release:
    name: release
    runs-on: ubuntu-latest
    needs: test
    if: github.event.push || github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
